require("atomicvim.plugins-setup")
require("atomicvim.core.options")
require("atomicvim.core.keymaps")
require("atomicvim.core.colorscheme")
require("atomicvim.plugins.comment")
require("atomicvim.plugins.nvim-tree")
require("atomicvim.plugins.lualine")
